DELETE FROM action_registry
WHERE action_name = 'promote_employee';

INSERT OR REPLACE INTO action_registry (
  action_name,
  phase,
  trigger_fields_json,
  trigger_condition,
  documents_json,
  recipients_json,
  is_active,
  created_at,
  updated_at
) VALUES
(
  'add_employee',
  'onboarding',
  '["status","hireDate"]',
  'status === ACTIVE && isNewRecord',
  '[
    {"id":"employment_contract","template":"employmentContract.html","order":1},
    {"id":"probation_order","template":"probationOrder.html","order":2},
    {"id":"job_description","template":"jobDescription.html","order":3},
    {"id":"nda","template":"nda.html","order":4}
  ]',
  '["hr_team","department_chief","branch_manager"]',
  1,
  datetime('now'),
  datetime('now')
),
(
  'salary_increase',
  'working',
  '["level","numberOfVacationDays","isSalaryCompany"]',
  NULL,
  '[
    {"id":"salary_increase_order","template":"salaryIncreaseOrder.html","order":1}
  ]',
  '["hr_team","department_chief"]',
  1,
  datetime('now'),
  datetime('now')
),
(
  'change_position',
  'working',
  '["department","branch","level"]',
  NULL,
  '[
    {"id":"job_description","template":"jobDescription.html","order":1},
    {"id":"position_update_order","template":"positionUpdateOrder.html","order":2},
    {"id":"contract_addendum","template":"contractAddendum.html","order":3}
  ]',
  '["hr_team","department_chief","branch_manager"]',
  1,
  datetime('now'),
  datetime('now')
),
(
  'offboard_employee',
  'offboarding',
  '["terminationDate","status"]',
  NULL,
  '[
    {"id":"termination_order","template":"terminationOrder.html","order":1},
    {"id":"handover_sheet","template":"handoverSheet.html","order":2}
  ]',
  '["hr_team","department_chief","ceo"]',
  1,
  datetime('now'),
  datetime('now')
);
